import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../src/Header/Header.jsx";
import Footer from "../src/Footer/Footer.jsx";
const inter = Inter({ subsets: ["latin"] });
import Clicker from "../src/Clicker/Clicker.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Header title="Fireplace Palace" />
          <Clicker onClick={handleClick} />

          <Footer />
        </div>
      </body>
    </html>
  );
}
