// RootLayout.jsx
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../src/Header/Header.jsx";
import Footer from "../src/Footer/Footer.jsx";
import { useClient } from "next/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  useClient();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Header title="Fireplace Palace" />
          <Footer />

          <Footer />
        </div>
      </body>
    </html>
  );
}
